tile: "Homelab Stacks"
remote_theme: "pmarsceill/just-the-docs"
url: "https://regnerba.com"
baseurl: "/homelab-stacks"
search_enabled: true
permalink: pretty
aux_links:
  "GitHub":
  - "https://github.com/regner/homelab-stack"
